# Generated by Django 3.2.3 on 2021-06-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
